[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/golang/geo"

[[constraint]]
  branch = "master"
  source = "https://github.com/abh/tail.git"
  name = "github.com/hpcloud/tail"

[[constraint]]
  branch = "master"
  name = "github.com/miekg/dns"

[[constraint]]
  branch = "master"
  name = "github.com/oschwald/geoip2-golang"

[[constraint]]
  branch = "master"
  name = "github.com/stretchr/testify"

[[constraint]]
  version = "^v1.4.7"
  name = "github.com/fsnotify/fsnotify"

[[constraint]]
  version = "v1.2.1"
  name = "gopkg.in/gcfg.v1"

[[constraint]]
  branch = "v2.0"
  name = "gopkg.in/natefinch/lumberjack.v2"

