[prune]
  non-go = true
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/golang/geo"

[[constraint]]
  branch = "master"
  name = "github.com/hpcloud/tail"

[[constraint]]
  branch = "master"
  name = "github.com/influxdata/influxdb"

[[constraint]]
  branch = "master"
  name = "github.com/kr/pretty"

[[constraint]]
  branch = "master"
  name = "github.com/miekg/dns"

[[constraint]]
  branch = "master"
  name = "github.com/oschwald/geoip2-golang"

[[constraint]]
  branch = "master"
  name = "github.com/stretchr/testify"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  version = "v1.4.7"
  name = "gopkg.in/fsnotify.v1"

[[constraint]]
  version = "v1.2.1"
  name = "gopkg.in/gcfg.v1"

[[constraint]]
  branch = "v2.0"
  name = "gopkg.in/natefinch/lumberjack.v2"

